### ISSUE TITLE
engine.Line draws mirrored if x2 < x1

### ISSUE THREAD

**Issue by ldb** [bjatkin/go-fantasy-engine#1]
When using engine.Line the line is drawn mirrored if x2 < x1
Example:

```go
func draw() {
	g.Cls(golf.Col7)
	g.RectFill(100, 100, 2, 2, golf.Col3) // Starting point
	mx, my := g.RAM[0x360D], g.RAM[0x360E] // Mouse Coordinates
	g.RectFill(float64(mx), float64(my), 2, 2, golf.Col5) // Target point
	g.Line(100, 100, float64(mx), float64(my), golf.Col0)
}
```

This code draws the line correctly as long the mouse pointer is on the right of the starting point:

<img width="300" alt="91043075-2f446500-e613-11ea-8757-e7b81e0f099e" src="https://user-images.githubusercontent.com/10501668/91043075-2f446500-e613-11ea-8757-e7b81e0f099e.png">

However, as soon as I move the mouse to the left of the starting point, the line is mirrored horizontally and vertically:

<img width="300" alt="91043100-408d7180-e613-11ea-8f23-adb24cbcc2db" src="https://user-images.githubusercontent.com/10501668/91043100-408d7180-e613-11ea-8f23-adb24cbcc2db.png">
<img width="300" alt="91043101-41260800-e613-11ea-8f3e-8c2b269fea2c" src="https://user-images.githubusercontent.com/10501668/91043101-41260800-e613-11ea-8f3e-8c2b269fea2c.png">

My expectation would be that the line is always drawn directly between (x1, y1) and (x2, y2).
Am I maybe using engine.Line incorrectly in some way?

Thank you!

**Comment by bjatkin** [comment]
Thanks for bringing this to my attention. I've changed the code to use the digital differential analyzer algorithm for drawing lines. This issue should now be resolved.
![fixedLine1](https://user-images.githubusercontent.com/29131617/91251866-90eef700-e719-11ea-8534-f877284ea475.png)
![fixedLine2](https://user-images.githubusercontent.com/29131617/91251877-951b1480-e719-11ea-89c9-a899d264a7a8.png)
